/**
 * Service Worker registration with strong guards for Lovable preview/iframe
 * contexts. In those contexts the SW must NEVER register (and any previously
 * registered SW should be unregistered) to avoid stale-cache problems.
 *
 * In production on the real domain, it registers a NetworkFirst-backed SW so
 * the menu and main pages remain available offline.
 */
export function registerServiceWorker() {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;

  const isInIframe = (() => {
    try {
      return window.self !== window.top;
    } catch {
      return true;
    }
  })();

  const host = window.location.hostname;
  const isPreviewHost =
    host.includes("id-preview--") ||
    host.includes("lovableproject.com") ||
    host.includes("lovable.app") === false && host === "localhost";

  const isLocalhost = host === "localhost" || host === "127.0.0.1";

  if (isInIframe || isPreviewHost || isLocalhost || import.meta.env.DEV) {
    // Aggressively clean up any leftover SW + caches in preview/iframe/dev
    navigator.serviceWorker.getRegistrations().then((regs) => {
      regs.forEach((r) => r.unregister().catch(() => {}));
    });
    if ("caches" in window) {
      caches.keys().then((keys) => keys.forEach((k) => caches.delete(k).catch(() => {})));
    }
    return;
  }

  // Real production host — register the SW generated by vite-plugin-pwa.
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      registerSW({
        immediate: true,
        onRegisteredSW(_swUrl, registration) {
          // Check for updates every hour while the tab is open.
          if (registration) {
            setInterval(() => registration.update().catch(() => {}), 60 * 60 * 1000);
          }
        },
      });
    })
    .catch(() => {
      // Silent: PWA registration is a non-critical enhancement.
    });
}